### PR TITLE
Feat : Create Task Actions | Loader

### PR DESCRIPTION
**Pull request by rehanmohiuddin**
- Added Tasks CRUD API's In Backend
- Added Loader Component
- Added Context
- Added Actions
- Added API services

### CODE REVIEW

**Review by abhijeetekad — APPROVED** [review]
I like how you implemented a rich text editor. Great job

**Review by abhijeetekad — APPROVED** [review]

**Comment by jDineshKarthic** [comment]
The modal doesn't close when the user clicks the cancel button.

**Comment by jDineshKarthic** [comment]
Change:
1. The background color(eg: green) to the tasks completed so that the user can differentiate.
2. The background color of the tasks that are in progress so that the user can quickly identify the present tasks.

**Comment by jDineshKarthic** [comment]
The event listeners for buttons Bold, Italic, and Strikethrough aren't working when the user clicks.

**Comment by rehanmohiuddin** [comment]
@jDineshKarthic this or is only for UI actions are there in latest PR Thanks for the review

**Review by aqsaaqeel — COMMENTED** [review]
I like how you have put your contexts in one context. And also how you have named the tasks

**Pull request merged**
